[workspace]
members = [
    "backends",
    "backends/candle",
    "backends/core",
    "backends/python",
    "backends/grpc-client",
    "core",
    "router",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Olivier Dehaene"]
homepage = "https://github.com/huggingface/text-embeddings-inference"

[patch.crates-io]
cudarc = { git = "https://github.com/OlivierDehaene/cudarc", rev = "4c8e6d36a4a4c31e2e4649ae5246226452a01fc1" }
candle = { git = "https://github.com/OlivierDehaene/candle", rev = "b8a70c1166ef7c3e73ac79b2a63c14931edabb90", package = "candle-core" }
candle-nn = { git = "https://github.com/OlivierDehaene/candle", rev = "b8a70c1166ef7c3e73ac79b2a63c14931edabb90", package = "candle-nn" }
candle-transformers = { git = "https://github.com/OlivierDehaene/candle", rev = "b8a70c1166ef7c3e73ac79b2a63c14931edabb90", package = "candle-transformers" }
candle-flash-attn = { git = "https://github.com/OlivierDehaene/candle", rev = "b8a70c1166ef7c3e73ac79b2a63c14931edabb90", package = "candle-flash-attn" }

[profile.release]
debug = 1
incremental = true
lto = "off"
panic = "abort"
